config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"

  root to: "home#index"

  resources :contacts, only: :index
  resources :home, only: :index
  resources :works, only: [ :index, :show ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact.rb
# == Schema Information
#
# Table name: contacts
#
#  id         :integer          not null, primary key
#  name       :string
#  url        :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Contact < ApplicationRecord
    validates :name, presence: true

    def safe_url
        uri = URI.parse(url)
        uri.to_s if uri.is_a?(URI::HTTP)
    rescue URI::InvalidURIError
        nil
    end
end

app/models/image.rb
# == Schema Information
#
# Table name: images
#
#  id         :integer          not null, primary key
#  file_name  :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  work_id    :integer          not null
#
# Indexes
#
#  index_images_on_work_id  (work_id)
#
# Foreign Keys
#
#  work_id  (work_id => works.id)
#
class Image < ApplicationRecord
  belongs_to :work
end

app/models/work.rb
# == Schema Information
#
# Table name: works
#
#  id          :integer          not null, primary key
#  description :text
#  name        :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Work < ApplicationRecord
    validates :name, presence: true
    validates :description, presence: true

    has_many :images, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
    @contacts = Contact.all
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
  end
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  def index
    @works = Work.all
  end

  def show
    @work = Work.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/contacts/index.html.erb
<h1><%= t ".title" %></h1>

<div id="contacts">
    <% @contacts.each do |contact| %>
        <div>
            <% if contact.url.present? %>
                <%= link_to contact.name, contact.safe_url.to_s %>
            <% else %>
                <%= contact.name %>
            <% end %>        
        </div>
    <% end %>
</div>

app/views/home/index.html.erb
<h1>Welcome to my portfolio page!</h1>
<div class="home">
  <div class="home_container">
    <h2>introduction</h2>
    <p>Hello, my name is Nanami.</p>
    <p>I developed an interest in programming when I was at a stage of re-evaluating my career.</p>
    <p>I initially started studying programming out of simple curiosity.</p>
    <p>As I continued learning, I discovered the excitement of building applications with my own hands.</p>
    <p>That passion still drives me today, and I continue to feel inspired by the joy of seeing the code I write come to life directly in the system.</p>
    <p>Recently, I have been staying in Sydney to broaden both my skills and perspectives.</p>
    <p>I am now looking for new opportunities in global positions where I can continue to grow and contribute.</p>
  </div>

  <div class="home_container">
    <h2>about me</h2>
    <p>I'm a software engineer passionate about building scalable web applications and thoughtful user experiences. </p>
    <p>With a background in Ruby on Rails, JavaScript, and AWS, I’ve contributed to large-scale systems including an AI-powered transportation demand app that reached No.1 market share in Japan.</p>
    <p>I enjoy creating clean, intuitive interfaces and solving real-world problems through code.</p>
    <p>Outside of coding, I have always enjoyed physical activities, starting with the sports I was passionate about during my student days.</p>
    <p>Recently, I’ve become particularly interested in spending time in nature, and I enjoy activities like fishing and camping.</p>
    <p>I value both the time I spend in front of the screen and the time I spend connecting with the outdoors.</p>
  </div>
</div>

app/views/layouts/_header.erb
<div class="tab-container">
  <ul>
    <li><%= button_to "Home", root_path, method: :get %></li>
    <li><%= button_to "Projects", projects_path, method: :get %></li>
    <li><%= button_to "Contact", contacts_path, method: :get %></li>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Portfolio" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <nav>
        <%= link_to "Home", root_path %>
        <%= link_to "Works", works_path %>
        <%= link_to "Contacts", contacts_path %>
      </nav>
    </header>

    <main>
      <div id="container">
        <%= yield %>
      </div>
    </main>
  </body>
</html>

app/views/projects/_project-tab.erb
<ul>
    <p>Summary:</p>
    <li>Developed a on-demand transportation system, which achieved top market share in Japan during development.</li>
</ul>
<div class="devide_center">
    <div class="left">
        <p>Tech Used:</p>
        <p>Ruby on Rails, AWS, JavaScript, HTML/CSS</p>
    </div>
    <div class="right">
        <p><%= image_tag 'ruby.png', alt: 'Ruby', class: 'icon' %></p>
        <p><%= image_tag 'aws-icon.png', alt: 'AWS', class: 'icon' %></p>
        <p><%= image_tag 'javascript-y.png', alt: 'JavaScript', class: 'icon' %></p>
    </div>
</div>



<!--タブ部分-->
<ul class="tab-list list-unstyled">
  <li class="tab tab-active">
    My Role & Contributions
  </li>
  <li class="tab">
    System Overview
  </li>
  <li class="tab">
    Key Features
  </li>
</ul>

<!--タブで選択された要素部分-->
<div class="tabbox-contents">
  <div class="tabbox box-show">
    <li>Designed and implemented backend features using Ruby on Rails, focusing on scalability and performance</li>
    <li>Developed a patented notification system to enhance communication and streamline operations</li>
    <li>Integrated Google reCAPTCHA for secure and user-friendly authentication</li>
    <li>Managed cloud infrastructure using AWS services and Terraform, ensuring stability and automation</li>
    <li>Contributed to Android app development (Java/Kotlin) to support mobile user accessibility</li>
    <li>Led and collaborated in Agile sprints to continuously improve system quality and delivery speed</li>
    <li>Provided direct customer support, solving technical issues and improving user satisfaction</liß>

    <div class='note'>Note: source code not publicly available due to company policy.</div>
  </div>
  <div class="tabbox">
    <li>Consumer App (PC/mobile): Riders book their trip by selecting departure and arrival points</li>
    <li>Operator App: Staff manage incoming bookings and vehicle operations in real time</li>
    <li>Reporting Dashboard: Service providers monitor metrics, demand, and performance</li>
    <li>Driver App:vBus/taxi drivers receive updated routes and instructions</li>
  </div>
  <div class="tabbox">
    <li>Dynamic route generation using external APIs (e.g., Google API, Directions API)</li>
    <li>Real-time re-routing when new reservations are added</li>
    <li>Parameter-based route logic configurable by service providers</li>
    <li>Scalable backend architecture handling multiple services</li>
  </div>
</div>

# <ul>
#     <p>My Role & Contributions:</p>

#     <li>Designed and implemented backend features using Ruby on Rails, focusing on scalability and performance</li>
#     <li>Developed a patented notification system to enhance communication and streamline operations</li>
#     <li>Integrated Google reCAPTCHA for secure and user-friendly authentication</li>
#     <li>Managed cloud infrastructure using AWS services and Terraform, ensuring stability and automation</li>
#     <li>Contributed to Android app development (Java/Kotlin) to support mobile user accessibility</li>
#     <li>Led and collaborated in Agile sprints to continuously improve system quality and delivery speed</li>
#     <li>Provided direct customer support, solving technical issues and improving user satisfaction</liß>
# </ul>
# <div class='note'>Note: source code not publicly available due to company policy.</div>

# <ul>
#     <p>System Overview:</p>
#     <li>Consumer App (PC/mobile): Riders book their trip by selecting departure and arrival points</li>
#     <li>Operator App: Staff manage incoming bookings and vehicle operations in real time</li>
#     <li>Reporting Dashboard: Service providers monitor metrics, demand, and performance</li>
#     <li>Driver App:vBus/taxi drivers receive updated routes and instructions</li>
# </ul>

# <ul>
#     <p>Key Features:</p>
#     <li>Dynamic route generation using external APIs (e.g., Google API, Directions API)</li>
#     <li>Real-time re-routing when new reservations are added</li>
#     <li>Parameter-based route logic configurable by service providers</li>
#     <li>Scalable backend architecture handling multiple services</li>
# </ul>

app/views/projects/index.html.erb
<div class="section">
    <div class="container">
        <h1>Projects</h1>
            <h2>On-Demand Transportation System</h2>
                <%= render "project-tab" %>
    </div>
</div>
<div class="container">
    <div class="container">
        <h1>Skills & Tech Stack</h1>
            <div class="devided_3">
                <ul class="subheading"><p>Frameworks</p>
                    <li>Ruby on Rails</li>
                    <li>JavaScript</li>
                    <li>HTML</li>
                    <li>CSS</li>
                    <li>Java</li>
                </ul>
                <ul class="subheading"><p>DevOps</p>
                    <li>AWS (EC2, RDS, S3, CloudWatch)</li>
                    <li>Terraform</li>
                    <li>Jenkins</li>
                    <li>Git</li>
                </ul>
                <ul class="subheading"><p>Databases</p>
                    <li>MySQL</li>
                </ul>
            </div>

            <div class="devided_3">
                <ul class="subheading"><p>Tools & Platforms</p>
                    <li>Linux</li>
                    <li>GitHub</li>
                    <li>Docker</li>
                    <li>New Relic</li>
                </ul>
                
                <ul class="subheading"><p>Development Practices</p>
                    <li>Agile/Scrum</li>
                    <li>Test-Driven Development</li>
                    <li>Version Control</li>
                    <li>Debugging</li>
                </ul>
                
                <ul class="subheading"><p>Other Skills</p>
                    <li>System Design</li>
                    <li>UI/UX Design</li>
                    <li>Customer Support Communication</li>
                </ul>
            </div>
    </div>
</div>

app/views/works/index.html.erb
<h1><%= t ".title" %></h1>

<div id="works">
    <% @works.each do |work| %>
        <%= link_to work_path(work), class: "work-card" do %>
            <% if work.images.empty? %>
                <%= image_tag "no_image.png", class: "work-image" %>
            <% else %>
                <%= image_tag work.images.first.file_name, class: "work-image" %>
            <% end %>
                <h3 class="work-title"><%= work.name %></h3>
                <p class="work-description"><%= work.description.slice(0..200) %>...</p>
        <% end %>
    <% end %>
</div>

app/views/works/show.html.erb
<p><%= link_to "Back", works_path %></p>

<section class="work">
    <section class="work-info">
        <% cache @work do %>
            <h1><%= @work.name %></h1>
            <%= @work.description %>
        <% end %>
    </section>
</section>